### PR TITLE
add node tree builder

### PR DESCRIPTION
**Pull request by lamanhdai**
## Components:
- BaseNode: basic node
- LeafNode: active input, button state..
- TreeNode: contain BaseNode, LeafNode.
## Added:
- I used hook useReducer at App.js file to manage whole state of tree.
- I also passed dispatch action from useReducer into LeafNode and Form create a new Node.
- In reducer, I used `bfs` function with parameter tree and id Node to get a Node in Tree.
- Then I had Node from bfs function, I used `traverseNode` function to get add new Node into Tree.
## Refactored:
- Inside `bfs` function, I enhanced by breaking loop in `getNewNode` function if found id of Node.
- Inside `traverseNode` function, I enhanced by changing filter to map function to keep position of Node inside Tree when add a Node.

### CODE REVIEW

**Comment by longtran-pops** [comment]
Hi @lamanhdai 

Thanks for your time to complete the test.
I'm sorry to say that you haven't passed the test this time.

Regards.

**Review by longtran-pops — COMMENTED** [review]
Hi @lamanhdai,

I'm sorry about my unclear feedback last time. Because there is still another candidate who haven't submit his test until deadline.

In general, your solution is really good and clean. The idea to centralize the state and use dispatcher to update the state is a good solution. But It re-render the whole tree on every single change is hurting our performance. Let consider how to update a single node in the big tree (10 level depth and each node have 10 children). In the other hand, searching a node by BFS is not really necessary here as you can build a XPath while rendering a tree which could help you to find a node much faster.

Anyway, I'm open for any feedback about the test so that we can make it much better next time.
Thanks

**Comment by lamanhdai** [comment]
@longtran-pops I researched and didn't find XPath like you said. Could you give me a XPath example or clue?

**Comment by longtran-pops** [comment]
In Tree-Node data structure, XPath is the path expression which like a direction from the root node to a destination node.
in HTML document, a XPath could look like `html>body>div[1]>div[3]>span[1]` which express that I would like to get the first span - of the third div - of the first div - of the body - of the html.
In our case, an xPath could look like root>1>2 mean I would like get the second child of the first child of the root node. So, my code could get the target node like:

```
const child1 = root.children[0];
const dest = child1.children[1];
```
So, the complexity will be O(D) - D is the Depth level.

**Pull request closed without merging**
